<div id="modal" class="fixed inset-0 hidden bg-gray-500 bg-opacity-50 justify-center items-center">
    <div class="bg-white p-6 rounded-lg w-1/3 modal-position">
        <div class="flex justify-between items-center mb-4">
            <h3 class="text-xl font-semibold text-gray-800" id="modalTitle"></h3>
            <button id="closeModal" class="text-gray-600 hover:text-gray-900 focus:outline-none">&times;</button>
        </div>
        <div id="modalBody" class="text-gray-600"></div>
        <div class="mt-4 flex justify-end">
            <button id="closeBtn" class="px-4 py-2 bg-blue-500 text-white rounded hover:bg-blue-600 focus:outline-none"></button>
        </div>
    </div>
</div>