
<?php include_once('components/taskComponent.php'); ?>

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Tasques</title>
  <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="bg-white">
  <div class="flex h-screen">
    <div class="bg-white text-black p-6 flex flex-col justify-between border-r-2 mt-10">
      <h1 class="text-3xl font-bold mb-4 text-center">Accions</h1>
      <div class="flex flex-col flex-1">
        <div class="flex flex-col items-center group">
  <div class="relative">
    <button class="bg-black rounded-full text-white p-2 group-hover:bg-gray-800 focus:outline-none">
      <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6v6m0 0v6m0-6h6m-6 0H6"></path>
      </svg>
    </button>
  </div>
  <span class="mt-1 opacity-0 group-hover:opacity-100 group-hover:mb-4 transition-opacity">Crear</span>
</div>
<div class="flex flex-col items-center group">
  <div class="relative">
    <button class="bg-black rounded-full text-white p-2 group-hover:bg-gray-800 focus:outline-none">
      <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16"></path>
          </svg>
    </button>
  </div>
  <span class="mt-1 opacity-0 group-hover:opacity-100 group-hover:mb-4 transition-opacity">Editar</span>
</div>
<div class="flex flex-col items-center group">
  <div class="relative">
    <button class="bg-black rounded-full text-white p-2 group-hover:bg-gray-800 focus:outline-none">
          <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"></path>
          </svg>
    </button>
  </div>
  <span class="mt-1 opacity-0 group-hover:opacity-100 group-hover:mb-4 transition-opacity">Eliminar</span>
</div>
<hr/>
<h1 class="text-3xl font-bold mt-4 mb-4 text-center">Filtres</h1>
<div class="flex flex-col items-center group">
  <div class="relative">
    <button class="bg-green-600 rounded-full text-white p-2 group-hover:bg-green-700 focus:outline-none w-5 h-5">
    </button>
  </div>
  <span class="mt-1 opacity-0 group-hover:opacity-100 group-hover:mb-4 transition-opacity">Acabades</span>
</div>
<div class="flex flex-col items-center group">
  <div class="relative">
    <button class="bg-orange-300 rounded-full text-white p-2 group-hover:bg-orange-400 focus:outline-none w-5 h-5">
    </button>
  </div>
  <span class="mt-1 opacity-0 group-hover:opacity-100 group-hover:mb-4 transition-opacity">En curs</span>
</div>
<div class="flex flex-col items-center group">
  <div class="relative">
    <button class="bg-gray-300 rounded-full text-white p-2 group-hover:bg-gray-400 focus:outline-none w-5 h-5">
    </button>
  </div>
  <span class="mt-1 opacity-0 group-hover:opacity-100 group-hover:mb-4 transition-opacity">Pendents</span>
</div>

      </div>
    </div>
    <!-- MAIN DIV -->
    <div class="flex-1 p-6 overflow-y-auto">
      <h1 class="text-6xl font-bold mb-4 mt-4">Tasques</h1>
      <div class="row mb-4 ml-4 w-screen">
          <button class="text-gray-500 hover:text-gray-300 focus:outline-none">
          <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"></path>
          </svg>
        </button>
        <input class="bg-gray-200 rounded-md h-8 w-1/3 align-top" type="text" name="cercar" />
      </div>
      <!-- TASK GRID -->
      <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 max-w-5xl">
        <!-- TASKS HERE -->

        <?php 
            $tasks = $this->tasks;
            foreach($tasks as $task){
                new taskComponent($task);
            }
        ?>
      </div>
    </div>
  </div>
</body>
</html>