<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Crear tasca</title>
    <style>
        select:focus-visible {
            outline: none;  /* Elimina el contorno */
            border: none;    /* Elimina el borde */
        }
        </style>
</head>

<body>
    <div class="flex">
        <div class="flex-initial w-36" style="
        border-right: 1px solid #cfc1c1;
    height: 92vh;
    margin: 3% 5% 0 2%;
    "
    >
    
        <!-- Icono de "home" (outline) -->
        <i class="fa fa-arrow-left" aria-hidden="true"></i>
        <span>Tornar</span>
        </div>

        <div class="flex-0  w-[568px]">

            <h1 class="text-4xl mt-16 mb-7 font-bold">Crear</h1>

            <form action="/create" method="POST" class="w-full">

                <span class="flex flex-col my-7">
                    <label for="title" class="font-bold mb-2">Títol</label>
                    <input type="text" id="title" name="title" class="bg-gray-200 rounded-[20px] h-[54px] px-[15px]"
                        placeholder="Introdueix un titol per a la tasca" required>
                </span>

                <span class="flex flex-col mt-7">
                    <label for="description" class="font-bold mb-2">Descripció</label>
                    <textarea id="description" name="description" placeholder="Introdueix una descripció per a la tasca"
                        class="bg-gray-200 rounded-[20px] h-[100px] px-[15px] py-[10px]" rows="4" required></textarea>
                </span>

                <span class="flex justify-between">
                    <span class="flex flex-col my-7">
                        <label for="created_by" class="font-bold mb-2">Creat per</label>
                        <input type="text" id="created_by" name="created_by"
                            class="bg-gray-200 rounded-[20px] w-[221px] h-[34px] px-[15px]"
                            placeholder="Introdueix el teu nom" required>
                    </span>

                    <span class="flex flex-col my-7">
                        <label for="tags" class="font-bold mb-2">Tags (separat per comes):</label>
                        <input type="text" id="tags" name="tags" placeholder="ex: treball,reporte,urgent" required
                            class="bg-gray-200 rounded-[20px] w-[291px] h-[34px] px-[15px]">
                    </span>

                </span>

                <span class="flex">
                    <span class=" w-1/2">
                        <span class="flex">
                            <label for="start_time" class="font-bold mr-3">De:</label>
                            <input type="datetime-local" id="start_time" name="start_time" required class="">
                        </span>

                        <span class="flex">
                            <label for="end_time" class="font-bold mr-3">Fins:</label>
                            <input type="datetime-local" id="end_time" name="end_time" required class=" rounded-[20px]">
                        </span>
                    </span>

                    <div class="w-1/2 flex flex-col items-start">
                        <label for="state" class="font-bold mb-2">Estat:</label>
                        <div class="relative">
                            <select id="state" name="state" required
                                class="block w-full px-4 py-2 border border-gray-300 rounded-md border-none	"
                                onchange="updateCircle()">
                                <option value="ongoing">En curs</option>
                                <option value="completed">Complet</option>
                                <option value="pending">Pendent</option>
                            </select>

                            <div id="circle-container"
                                class="absolute inset-0 flex justify-between items-center pointer-events-none">
                                <span id="circle" class="w-2 h-2 bg-orange-500 rounded-full mr-2"></span>
                            </div>
                        </div>
                    </div>

                </span>

                <button class="my-9 bg-[#C76FA9] text-white	rounded-[18px] w-[164px] h-[45px]"
                    type="submit">Crear</button>
            </form>
        </div>
    </div>

    <script>
    function updateCircle() {
        const select = document.getElementById('state');
        const selectedValue = select.value;
        const circle = document.getElementById('circle');

        switch (selectedValue) {
            case 'ongoing':
                circle.className = 'w-2 h-2 bg-orange-500 rounded-full mr-2';
                break;
            case 'completed':
                circle.className = 'w-2 h-2 bg-green-500 rounded-full mr-2';
                break;
            case 'pending':
                circle.className = 'w-2 h-2 bg-gray-500 rounded-full mr-2';
                break;
        }
    }
</script>
</body>

</html>


<!-- 
Mensaje de error o de OK
O redirigir
Pasar valores exactos a %
-->