<div class='opacity-0 w-20 absolute right-4 bottom-0 group-hover/task:opacity-100 flex flex-row z-10 justify-end gap-4 align-end pb-1'>
  <div class='flex flex-col items-center group'>
    <a id='readBtn-id-placeholder' href='/view/id-placeholder' class='bg-black text-white rounded-full p-2 group-hover:bg-purple group-hover:text-white focus:outline-none'>
      <svg class='w-6 h-6' fill='none' stroke='currentColor' viewBox='0 0 24 24' xmlns='http://www.w3.org/2000/svg'>
      <path stroke-linecap='round' stroke-linejoin='round' stroke-width='2' d='M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z'></path>
    </svg>
</a>
    <span class='mt-1 opacity-0 text-xs group-hover:opacity-100 transition-opacity'>Veure</span>
  </div>
  <div class='flex flex-col items-center group'>
    <a id='editBtn-id-placeholder' href='/edit/id-placeholder' class='bg-black rounded-full text-white p-2 group-hover:bg-purple group-hover:text-white focus:outline-none'>
      <svg class='w-6 h-6' fill='none' stroke='currentColor' viewBox='0 0 14 14' xmlns='http://www.w3.org/2000/svg'>
      <path  stroke-linecap='round' stroke-linejoin='round' stroke-width='1' d='M7,1v6M7,7v6M7,7h6M7,7H1'/>
<path  stroke-linecap='round' stroke-linejoin='round' stroke-width='1' d='M11.24,2.76l-4.24,4.24M7,7l-4.24,4.24M7,7l4.24,4.24M7,7L2.76,2.76'/>
    </svg>
</a>
    <span class='mt-1 opacity-0 text-xs group-hover:opacity-100 transition-opacity'>Editar</span>
  </div>
</div>