<div id="modal" class="fixed inset-0 hidden bg-gray-500 bg-opacity-50 justify-center items-center">
    <div class="bg-white p-6 rounded-lg w-1/3 modal-position">
        <div class="flex justify-between items-center mb-4">
            <h3 class="text-xl font-semibold text-gray-800" id="modalTitle"></h3>
        </div>
        <div id="modalBody" class="text-gray-600"></div>
        <div id="buttonsContainer" class="mt-4 flex justify-end gap-2">
        </div>
    </div>
</div>