<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Editar tasca</title>
</head>

<body>
    <div class="flex">
        <div class="flex-initial w-36 bg-white text-black p-6 flex border-r-2 mt-10 back-icon">
            <i class="fa fa-arrow-left mt-[5px]" aria-hidden="true"></i>
            <span class="ml-[15px]" onclick="window.location.href='/'">Tornar</span>
        </div>

        <div class="flex-0  w-[568px]">

            <h1 class="text-6xl mt-16 mb-7 font-bold">Editar</h1>

            <form action="/edit/<?= $this->task['id'] ?>" method="POST" class="w-full">

                <span class="flex flex-col my-7">
                    <label for="title" class="font-bold mb-2">Títol</label>
                    <input type="text" id="title" name="title" class="bg-gray-200 rounded-[20px] h-[54px] px-[15px]"
                        value="<?= $this->task['title'] ?>">
                </span>

                <span class="flex flex-col mt-7">
                    <label for="description" class="font-bold mb-2">Descripció</label>
                    <textarea id="description" name="description"
                        class="bg-gray-200 rounded-[20px] h-[100px] px-[15px] py-[10px]" rows="4"><?= $this->task['description'] ?></textarea>
                </span>

                <span class="flex justify-between">
                    <span class="flex flex-col my-7">
                        <label for="created_by" class="font-bold mb-2">Creat per</label>
                        <input type="text" id="created_by" name="created_by"
                            class="bg-gray-200 rounded-[20px] w-[221px] h-[34px] px-[15px]"
                            value="<?= $this->task['created_by'] ?>">
                    </span>

                    <span class="flex flex-col my-7">
                        <label for="tags" class="font-bold mb-2">Tags (separat per comes):</label>
                        <input type="text" id="tags" name="tags" value="<?= implode(', ', $this->task['tags']) ?>"
                            class="bg-gray-200 rounded-[20px] w-[291px] h-[34px] px-[15px]">
                    </span>

                </span>

                <span class="flex">
                    <span class=" w-1/2 mt-3">
                        <span class="flex">
                            <label for="start_time" class="font-bold mr-3">De:</label>
                            <input type="datetime-local" value="<?= date("Y-m-d\TH:i:s", $this->task['start_time']) ?>" id="start_time" name="start_time" class="">
                        </span>

                        <span class="flex">
                            <label for="end_time" class="font-bold mr-3">Fins:</label>
                            <input type="datetime-local" id="end_time" value="<?= date("Y-m-d\TH:i:s", $this->task['end_time']) ?>" name="end_time" class=" rounded-[20px]">
                        </span>
                    </span>

                    <div class="w-1/2 flex flex-col items-start">
                        <label for="state" class="font-bold mb-2">Estat:</label>
                        <div class="relative">
                            <select id="state" name="state"
                                class="block w-full px-4 py-2 border border-gray-300 rounded-md border-none	"
                                onchange="updateCircle()">
                                <option value="ongoing" <?= $this->task['state'] === 'ongoing' ? 'selected' : '' ?>>En curs</option>
                                <option value="done" <?= $this->task['state'] === 'done' ? 'selected' : '' ?>>Complet</option>
                                <option value="pending" <?= $this->task['state'] === 'pending' ? 'selected' : '' ?>>Pendent</option>
                            </select>

                            <div id="circle-container"
                                class="absolute inset-0 flex justify-between items-center pointer-events-none">
                                <span id="circle" class="w-2 h-2 bg-orange-500 rounded-full mr-2"></span>
                            </div>
                        </div>
                    </div>

                </span>

                <button class="my-9 bg-purple text-white rounded-[18px] w-[164px] h-[45px]" type="submit">Editar</button>
            </form>
        </div>
    </div>
    <script>updateCircle();</script>
    <?php include dirname(__DIR__, 1) . '/components/html/modal.phtml'; ?>
    </div>
  </div>
</div>
</body>

</html>